[project]
    dependencies=[
        "django-cors-headers>=4.9.0",
        "django>=6.0.7",
        "djangorestframework>=3.17.1",
        "pillow>=12.3.0",
        "python-dotenv>=1.2.2",
        "requests>=2.34.2",
    ]
    description=""
    name="backend"
    readme="README.md"
    requires-python=">=3.13"
    version="0.1.0"
